apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-subchart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/christianh814/kbe-apps.git'
    path: /02-working-with-helm/repo/
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination: 
    server: https://kubernetes.default.svc
    namespace: test

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
