apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-test
  namespace: argocd
spec:
  project: default
  source:
    chart: jenkins-test
    repoURL: https://gitlab.com/jtodic1/jenkins-test.git
    targetRevision: 0.1.0
    helm:
      releaseName: jenkins-test
  destination: 
    server: https://kubernetes.default.svc
    namespace: test

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
