apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-jenkins
spec:
  selector:
    matchLabels:
      app: myapp-jenkins
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp-jenkins
    spec:
      containers:
      - name: myapp-jenkins
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
        ports:
        - containerPort: 8080
